### ISSUE TITLE
any way to stretch low end down to ~75MHz?

### ISSUE THREAD

**Issue by akohlsmith** [xaxaxa-dev/vna#15]
This is a fascinating project, thank you for your hard work!

I am wondering if it is possible to tweak the component selection to extend the low end down to include the broadcast FM range (88-108MHz), as I'd like to experiment with some filters in that area. Is such a thing possible with this design?

**Comment by xaxaxa** [comment]
It's possible; the two synthesizers (adf4350) need to be replaced with adf4351 which will bring lower frequency limit down to 35MHz. There are plans to switch to adf4351 by default in an upcoming hardware revision.

**Comment by kf4mot** [comment]
Any estimate on when the 35MHz version will be available?

**Comment by xaxaxa** [comment]
@kf4mot probably by Q2 2019
