### ISSUE TITLE
Any plans for a version with increased freq?

### ISSUE THREAD

**Issue by kf4mot** [xaxaxa-dev/vna#19]
Ideally up to 6 GHz+

**Comment by xaxaxa** [comment]
None at the moment, but there is another open source VNA design that can go up to 6GHz: http://hforsten.com/improved-homemade-vna.html

**Comment by kf4mot** [comment]
Or this may be a viable solution if freq. is scaled up. I probably even have most of the mixers, oscillator, and filters in my junk box.
