### ISSUE TITLE
Part numbers for U204, U205 and U206

### ISSUE THREAD

**Issue by NiklasFauth** [xaxaxa-dev/vna#26]
Hey,

I'm missing the part numbers for these filters. I guess one of them is LP0603A2140ANTR and another is LP0603A0947ANTR, but which filter is used where?

Also, there is a mismatch between PE4302 in the schematic and PE4312 in the description and AP4329 in the schematic and AP4319 in the BOM.

I would love to get some clarification, and ideally an up-to-date BOM for main2_2. Thanks!

Best
Niklas

**Comment by xaxaxa** [comment]
In gschem if you double click on the component you will see the hidden attributes that say U204 is LP0603A0947 for example. The real part numbers used in production are in the main2_2.mapping.csv file, which is used by a script to generate the production BOM.

**Comment by NiklasFauth** [comment]
I haven't used gEDA before, thanks for the clearification!

Best,
Niklas
